/// Preset catalogue for the premium site builder.
///
/// Layout and CSS live in `assets/templates/blocks/` and are assembled
/// deterministically, so the page is always well-designed regardless of what
/// the coder model produces. The model only ever supplies copy, and every
/// token here doubles as the fallback when it does not.
library;

/// Canonical page order. Selected blocks are always emitted in this sequence,
/// so a student cannot produce a page with the footer above the hero.
const kSectionOrder = <String>[
  'nav',
  'hero',
  'stats',
  'features',
  'about',
  'services',
  'gallery',
  'testimonials',
  'pricing',
  'team',
  'faq',
  'cta',
  'contact',
  'footer',
];

/// Sections that every site gets; not offered as toggles.
const kCoreBlocks = <String>{'nav', 'hero', 'about', 'contact', 'footer'};

/// Anchor labels for the generated nav, keyed by block id.
const kNavLabels = <String, String>{
  'features': 'Features',
  'about': 'About',
  'services': 'Services',
  'gallery': 'Gallery',
  'testimonials': 'Reviews',
  'pricing': 'Pricing',
  'team': 'Team',
  'faq': 'FAQ',
  'contact': 'Contact',
};

/// A block a student can switch on or off before building.
class SiteFeature {
  const SiteFeature(this.blockId, this.label, this.blurb, {this.on = false});

  final String blockId;
  final String label;
  final String blurb;

  /// Pre-ticked for this vertical.
  final bool on;
}

class SiteVertical {
  const SiteVertical({
    required this.id,
    required this.name,
    required this.emoji,
    required this.brand,
    required this.brand2,
    required this.features,
    required this.copy,
  });

  final String id;
  final String name;
  final String emoji;

  /// Gradient pair driving the whole generated palette.
  final String brand;
  final String brand2;

  final List<SiteFeature> features;

  /// Default copy for this vertical, layered over [kBaseCopy].
  final Map<String, String> copy;

  Set<String> get defaultBlocks => {
        ...kCoreBlocks,
        ...features.where((f) => f.on).map((f) => f.blockId),
      };
}

/// Generic copy that reads well for any business, overridden per vertical.
const kBaseCopy = <String, String>{
  'cta_label': 'Get in touch',
  'trust_line': 'Trusted by our community',
  'eyebrow': 'Welcome',
  'features_eyebrow': 'What we offer',
  'features_title': 'Built around what you need',
  'features_intro': 'Everything we do is designed to be practical, dependable and genuinely useful.',
  'feature1_title': 'Quality first',
  'feature1_text': 'We hold every detail to a standard we would be happy to put our name on.',
  'feature2_title': 'People who care',
  'feature2_text': 'A team that listens properly and takes the time to get things right.',
  'feature3_title': 'Fair and honest',
  'feature3_text': 'Clear pricing, clear timelines, and no surprises along the way.',
  'about_eyebrow': 'Our story',
  'about_title': 'Who we are',
  'about_text': 'We started with a simple idea and a lot of determination, and we have been refining it ever since.',
  'about_point1': 'Rooted in the community we serve',
  'about_point2': 'Experienced, friendly and dependable',
  'about_point3': 'Committed to doing right by every person',
  'services_eyebrow': 'Services',
  'services_title': 'How we can help',
  'services_intro': 'A focused set of services, each delivered properly.',
  'service1_title': 'Consultation',
  'service1_text': 'We start by understanding exactly what you are trying to achieve.',
  'service2_title': 'Delivery',
  'service2_text': 'Careful, well-executed work delivered when we said it would be.',
  'service3_title': 'Support',
  'service3_text': 'We stay available long after the work itself is finished.',
  'service4_title': 'Follow-up',
  'service4_text': 'We check back in to make sure everything is still working for you.',
  'stat1_value': '10+',
  'stat1_label': 'Years of experience',
  'stat2_value': '500+',
  'stat2_label': 'People served',
  'stat3_value': '4.9',
  'stat3_label': 'Average rating',
  'stat4_value': '98%',
  'stat4_label': 'Would recommend',
  'gallery_eyebrow': 'Gallery',
  'gallery_title': 'A look at our work',
  'testimonials_eyebrow': 'Testimonials',
  'testimonials_title': 'What people say',
  'quote1_text': 'Genuinely excellent from start to finish. I would not hesitate to recommend them.',
  'quote1_name': 'Amina K.',
  'quote1_role': 'Customer',
  'quote2_text': 'Professional, friendly and they did exactly what they promised.',
  'quote2_name': 'Daniel O.',
  'quote2_role': 'Customer',
  'quote3_text': 'The care they put into their work really shows. Very happy.',
  'quote3_name': 'Grace N.',
  'quote3_role': 'Customer',
  'pricing_eyebrow': 'Pricing',
  'pricing_title': 'Simple, honest pricing',
  'pricing_intro': 'Choose what fits. No hidden costs.',
  'tier1_name': 'Basic',
  'tier1_price': 'From 50,000',
  'tier1_text': 'Everything you need to get started.',
  'tier2_name': 'Standard',
  'tier2_price': 'From 120,000',
  'tier2_text': 'Our most popular option, with room to grow.',
  'tier3_name': 'Premium',
  'tier3_price': 'From 250,000',
  'tier3_text': 'The full experience, with priority support.',
  'team_eyebrow': 'Our team',
  'team_title': 'The people behind the work',
  'person1_name': 'Sarah M.',
  'person1_role': 'Founder',
  'person2_name': 'James T.',
  'person2_role': 'Operations',
  'person3_name': 'Peter A.',
  'person3_role': 'Lead',
  'person4_name': 'Mary L.',
  'person4_role': 'Support',
  'faq_eyebrow': 'Questions',
  'faq_title': 'Frequently asked',
  'faq_intro': 'If your question is not here, just get in touch.',
  'faq1_q': 'What are your opening hours?',
  'faq1_a': 'We are open Monday to Saturday, 8am to 6pm.',
  'faq2_q': 'Where are you located?',
  'faq2_a': 'You will find our address and a contact form at the bottom of this page.',
  'faq3_q': 'How do I get started?',
  'faq3_a': 'Send us a message and we will get back to you within one working day.',
  'faq4_q': 'Do you offer support afterwards?',
  'faq4_a': 'Yes. We stay available after the work is done.',
  'cta_title': 'Ready to get started?',
  'cta_text': 'Tell us what you need and we will take it from there.',
  'contact_eyebrow': 'Contact',
  'contact_title': 'Get in touch',
  'contact_text': 'We would be glad to hear from you. Send a message and we will reply shortly.',
  'form_title': 'Send a message',
  'form_button': 'Send message',
  'email': 'hello@example.com',
  'phone': '+256 700 123 456',
  'address': 'Kampala, Uganda',
  'footer_note': 'Built by a student with AI Connect Africa.',
};

const _standardExtras = <SiteFeature>[
  SiteFeature('stats', 'Key numbers', 'A band of headline figures', on: true),
  SiteFeature('features', 'Highlights', 'Three things that set you apart', on: true),
  SiteFeature('services', 'Services list', 'Four services in detail'),
  SiteFeature('gallery', 'Photo gallery', 'A visual grid of your work'),
  SiteFeature('testimonials', 'Testimonials', 'What customers say'),
  SiteFeature('pricing', 'Pricing table', 'Three pricing tiers'),
  SiteFeature('team', 'Team', 'Introduce the people'),
  SiteFeature('faq', 'FAQ', 'Answer common questions'),
  SiteFeature('cta', 'Call to action', 'A closing prompt to act'),
];

const kVerticals = <SiteVertical>[
  SiteVertical(
    id: 'school',
    name: 'School',
    emoji: '🎓',
    brand: '#2563eb',
    brand2: '#7c3aed',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Excellence through education',
      'features_eyebrow': 'Why families choose us',
      'features_title': 'An education that opens doors',
      'feature1_title': 'Strong academics',
      'feature1_text': 'A rigorous curriculum taught by teachers who know every student by name.',
      'feature2_title': 'Character first',
      'feature2_text': 'We build discipline, confidence and integrity alongside examination results.',
      'feature3_title': 'Modern facilities',
      'feature3_text': 'Well-equipped laboratories, a stocked library and safe, welcoming grounds.',
      'services_title': 'Our programmes',
      'service1_title': 'Primary school',
      'service2_title': 'Lower secondary',
      'service3_title': 'Upper secondary',
      'service4_title': 'Clubs and sport',
      'stat1_value': '850',
      'stat1_label': 'Students enrolled',
      'stat2_value': '45',
      'stat2_label': 'Qualified teachers',
      'stat3_value': '15',
      'stat3_label': 'Years serving',
      'stat4_value': '92%',
      'stat4_label': 'Pass rate',
      'cta_title': 'Applications are open',
      'cta_label': 'Apply now',
      'team_title': 'Meet our teachers',
    },
  ),
  SiteVertical(
    id: 'bakery',
    name: 'Bakery / Restaurant',
    emoji: '🥐',
    brand: '#b45309',
    brand2: '#e11d48',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Baked fresh every morning',
      'features_title': 'Made properly, every single day',
      'feature1_title': 'Baked at dawn',
      'feature1_text': 'Everything leaves the oven hours before it reaches you.',
      'feature2_title': 'Local ingredients',
      'feature2_text': 'We buy from growers and millers we actually know.',
      'feature3_title': 'Made to order',
      'feature3_text': 'Cakes and platters for birthdays, weddings and events.',
      'services_title': 'On the menu',
      'service1_title': 'Fresh bread',
      'service2_title': 'Cakes and pastries',
      'service3_title': 'Coffee and tea',
      'service4_title': 'Event catering',
      'cta_title': 'Order something wonderful',
      'cta_label': 'Order now',
    },
  ),
  SiteVertical(
    id: 'portfolio',
    name: 'Personal Portfolio',
    emoji: '👤',
    brand: '#0ea5e9',
    brand2: '#6366f1',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Student developer & designer',
      'features_eyebrow': 'What I do',
      'features_title': 'Things I build',
      'feature1_title': 'Web development',
      'feature1_text': 'Responsive sites built with clean, readable HTML and CSS.',
      'feature2_title': 'Mobile apps',
      'feature2_text': 'Simple, useful applications that solve a real problem.',
      'feature3_title': 'Design',
      'feature3_text': 'Interfaces that are clear, accessible and pleasant to use.',
      'about_title': 'About me',
      'services_title': 'Selected projects',
      'stat1_value': '12',
      'stat1_label': 'Projects built',
      'stat2_value': '8',
      'stat2_label': 'Technologies used',
      'stat3_value': '3',
      'stat3_label': 'Years learning',
      'stat4_value': '6',
      'stat4_label': 'Certificates earned',
      'cta_title': 'Let us work together',
      'cta_label': 'Hire me',
      'footer_note': 'Portfolio built with AI Connect Africa.',
    },
  ),
  SiteVertical(
    id: 'church',
    name: 'Church / Ministry',
    emoji: '⛪',
    brand: '#7c3aed',
    brand2: '#2563eb',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Everyone is welcome here',
      'features_title': 'Come as you are',
      'feature1_title': 'Sunday worship',
      'feature1_text': 'Two services every Sunday, with children’s church alongside.',
      'feature2_title': 'Small groups',
      'feature2_text': 'Midweek gatherings where people know and support one another.',
      'feature3_title': 'Community outreach',
      'feature3_text': 'Practical service to our neighbourhood, every week of the year.',
      'services_title': 'Our ministries',
      'cta_title': 'Join us this Sunday',
      'cta_label': 'Plan a visit',
      'team_title': 'Our leadership',
    },
  ),
  SiteVertical(
    id: 'fitness',
    name: 'Gym / Fitness',
    emoji: '💪',
    brand: '#059669',
    brand2: '#0ea5e9',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Stronger starts today',
      'features_title': 'Training that actually works',
      'feature1_title': 'Expert coaching',
      'feature1_text': 'Certified trainers who build a plan around your body and goals.',
      'feature2_title': 'Open early, late',
      'feature2_text': 'Sessions that fit around school, work and family.',
      'feature3_title': 'Real community',
      'feature3_text': 'People who show up for each other, not just for the weights.',
      'services_title': 'Our programmes',
      'cta_title': 'First session is free',
      'cta_label': 'Start training',
    },
  ),
  SiteVertical(
    id: 'hotel',
    name: 'Hotel / Lodge',
    emoji: '🏨',
    brand: '#0f766e',
    brand2: '#a16207',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Rest well, stay longer',
      'features_title': 'A comfortable place to land',
      'feature1_title': 'Quiet, clean rooms',
      'feature1_text': 'Properly made beds, reliable water and power, and good sleep.',
      'feature2_title': 'Real food',
      'feature2_text': 'Breakfast included, with an à la carte kitchen open all day.',
      'feature3_title': 'Easy to reach',
      'feature3_text': 'Secure parking, simple directions and helpful staff on arrival.',
      'services_title': 'Rooms and rates',
      'pricing_title': 'Room rates',
      'cta_title': 'Book your stay',
      'cta_label': 'Check availability',
    },
  ),
  SiteVertical(
    id: 'ngo',
    name: 'NGO / Non-profit',
    emoji: '🤝',
    brand: '#0891b2',
    brand2: '#16a34a',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Working for lasting change',
      'features_title': 'How we make a difference',
      'feature1_title': 'Community-led',
      'feature1_text': 'Every programme is designed with the people it serves, not for them.',
      'feature2_title': 'Transparent',
      'feature2_text': 'We publish what we raise and exactly where it goes.',
      'feature3_title': 'Measured impact',
      'feature3_text': 'We track outcomes honestly, including the ones that fall short.',
      'services_title': 'Our programmes',
      'stat1_value': '12,000+',
      'stat1_label': 'People reached',
      'stat2_value': '34',
      'stat2_label': 'Communities',
      'stat3_value': '9',
      'stat3_label': 'Active programmes',
      'stat4_value': '87%',
      'stat4_label': 'Goes to programmes',
      'cta_title': 'Stand with us',
      'cta_label': 'Donate',
    },
  ),
  SiteVertical(
    id: 'realtor',
    name: 'Real Estate',
    emoji: '🏠',
    brand: '#1d4ed8',
    brand2: '#0f766e',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Find the right place',
      'features_title': 'Property done properly',
      'feature1_title': 'Verified listings',
      'feature1_text': 'Every title checked before a property reaches our books.',
      'feature2_title': 'Honest valuations',
      'feature2_text': 'A realistic price, explained, so you can decide with confidence.',
      'feature3_title': 'End to end',
      'feature3_text': 'From first viewing to final paperwork, handled in one place.',
      'services_title': 'What we handle',
      'cta_title': 'Looking to buy or sell?',
      'cta_label': 'Talk to an agent',
    },
  ),
  SiteVertical(
    id: 'salon',
    name: 'Salon / Barber',
    emoji: '💇',
    brand: '#be185d',
    brand2: '#7c3aed',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Look good, feel better',
      'features_title': 'Care you can see',
      'feature1_title': 'Skilled stylists',
      'feature1_text': 'Trained hands who listen before they pick up the scissors.',
      'feature2_title': 'Clean and careful',
      'feature2_text': 'Sterilised tools and fresh linen for every single client.',
      'feature3_title': 'Products that work',
      'feature3_text': 'Treatments chosen to suit your hair and skin, not just to sell.',
      'services_title': 'Our services',
      'pricing_title': 'Price list',
      'cta_title': 'Book your chair',
      'cta_label': 'Book now',
    },
  ),
  SiteVertical(
    id: 'techstartup',
    name: 'Tech Startup',
    emoji: '🚀',
    brand: '#4f46e5',
    brand2: '#06b6d4',
    features: _standardExtras,
    copy: {
      'eyebrow': 'Built for what comes next',
      'features_title': 'Why teams switch to us',
      'feature1_title': 'Fast to adopt',
      'feature1_text': 'Running in an afternoon, not a quarter. No consultants required.',
      'feature2_title': 'Works offline',
      'feature2_text': 'Built for real connectivity, not the connectivity of a demo.',
      'feature3_title': 'Priced for here',
      'feature3_text': 'Local pricing that reflects local realities, not a currency conversion.',
      'services_title': 'What you get',
      'stat1_value': '18k',
      'stat1_label': 'Active users',
      'stat2_value': '99.9%',
      'stat2_label': 'Uptime',
      'stat3_value': '7',
      'stat3_label': 'Countries',
      'stat4_value': '4.8',
      'stat4_label': 'Support rating',
      'cta_title': 'Start building today',
      'cta_label': 'Get started',
    },
  ),
];

SiteVertical? verticalById(String id) {
  for (final v in kVerticals) {
    if (v.id == id) return v;
  }
  return null;
}
