// Merges the per-language JSON that a sharded generator run leaves in
// tools/l10n_out/ into lib/l10n/ui_strings_generated.dart.
//
//   dart run tools/merge_ui_strings.dart
//
// generate_ui_strings.dart walks every language in one process, which the
// tool's own header rates in hours. CI gives each language its own job
// instead, so the wall clock is one language rather than nineteen; each job
// uploads tools/l10n_out/<code>.json and this stitches them back together.
import 'dart:convert';
import 'dart:io';

import 'package:ai_connect_africa/ai_core/translate/supported_languages.dart';

void main() {
  final keys = (jsonDecode(File('tools/l10n_keys.json').readAsStringSync())
          as List)
      .cast<String>();

  final dir = Directory('tools/l10n_out');
  if (!dir.existsSync()) {
    stderr.writeln('tools/l10n_out/ is missing — nothing to merge.');
    exit(1);
  }

  final tables = <String, Map<String, String>>{};
  for (final file in dir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.json'))) {
    final code = file.uri.pathSegments.last.replaceAll('.json', '');
    final raw = jsonDecode(file.readAsStringSync()) as Map;
    final table = raw.map((k, v) => MapEntry(k as String, v as String));
    if (table.isEmpty) continue;
    tables[code] = table;
    stdout.writeln('$code: ${table.length}/${keys.length}');
  }

  if (tables.isEmpty) {
    stderr.writeln('No non-empty shards in tools/l10n_out/ — refusing to '
        'write an empty table over a good one.');
    exit(1);
  }

  final buf = StringBuffer()
    ..writeln('// GENERATED by tools/generate_ui_strings.dart — do not edit.')
    ..writeln('//')
    ..writeln('// Machine translations of UI chrome, produced offline by')
    ..writeln('// TranslatePsy-AfriSLM. Consulted *after* the hand-curated')
    ..writeln('// kUiStrings and kUiStringsMore, so a reviewed entry always')
    ..writeln('// wins over anything here. Regenerate rather than hand-edit.')
    ..writeln('const kUiStringsGenerated = <String, Map<String, String>>{');

  var total = 0;
  for (final lang in supportedLanguages) {
    final table = tables[lang.code];
    if (table == null || table.isEmpty) continue;
    buf.writeln("  '${lang.code}': {");
    for (final key in keys) {
      final value = table[key];
      if (value == null) continue;
      buf.writeln("    '${_esc(key)}': '${_esc(value)}',");
      total++;
    }
    buf.writeln('  },');
  }
  buf.writeln('};');

  File('lib/l10n/ui_strings_generated.dart').writeAsStringSync(buf.toString());
  stdout.writeln('\nWrote lib/l10n/ui_strings_generated.dart — '
      '${tables.length} languages, $total strings.');
}

String _esc(String s) =>
    s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll('\n', r'\n');
